### PR TITLE
Save the data after removing player from guild rank

### PR DESCRIPTION
**Pull request by ncurran02**
This solves FS-134

### CODE REVIEW

**Comment by abhithedev200** [comment]
Hey, convert String name to lowercase.

**Comment by ncurran02** [comment]
> Hey, convert String name to lowercase.

Done

**Comment by abhithedev200** [comment]
Pr is good to merge, waiting for Ryan's confirmation.

**Comment by ncurran02** [comment]
@AtlasMediaGroup/totalfreedom-minecraft-developers Awaiting for the approval review.

**Comment by ncurran02** [comment]
Merging as it already have @abhiram555’s approval.

**Pull request merged**
